[project]
name = "practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "keras>=3.10.0",
    "opencv-python>=4.12.0.88",
    "roboflow>=1.2.1",
    "supervision>=0.25.1",
]
